# Navigation

index:
    path: /
    controller:

# Users

login:
    path: /accedi
    controller:

registrati:
    path: /registrati
    controller:

# Books
cataloga:
    path: /catalogo/crea
    controller:

#