# Navigation

index:
    path: /
    controller:

# Users

login:
    path: /accedi
    controller: App\Controller\UserController::login

registrati:
    path: /registrati
    controller: App\Controller\UserController::register

# Books
cataloga:
    path: /catalogo/crea
    controller: App\Controller\BookController::createBook

lista:
    path: /lista
    controller: App\Controller\BookController::bookList

#