#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller:

login:
    path: /accedi
    controller:

registrati:
    path: /registrati
    controller:

##crea nuovo libro
cataloga:
    path: /catalogo/crea
    controller:

##